version: '1.0'
services:
  db:
    platform: linux/amd64
    image: katushka/log-output-db:1.0
    build:
      context: ../log-output-project
      dockerfile: Dockerfile.db
  ping-pong:
    platform: linux/amd64
    image: katushka/ping-pong:1.9
    build:
      context: ../log-output-project
      dockerfile: Dockerfile.pingpong
  log-output:
    platform: linux/amd64
    image: katushka/log-output:1.9
    build:
      context: ../log-output-project
      dockerfile: Dockerfile.log-output
  timestamp-generator:
    platform: linux/amd64
    image: katushka/timestamp-generator:1.3
    build:
      context: ../log-output-project
      dockerfile: Dockerfile.timestamp