apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ping-pong-hpa
  namespace: log-output
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ping-pong-dep
  minReplicas: 1
  maxReplicas: 3
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: log-output-hpa
  namespace: log-output
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: log-output-dep
  minReplicas: 1
  maxReplicas: 3
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60


