apiVersion: v1
kind: Secret
metadata:
    namespace: log-output
    name: postgres-secret-config
type: Opaque
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Z/GNGcuAORoV0OIWA0KdAY+8NE5Msv0zRk0XVA==,iv:iUXgSei01V9gSzLPWPWUN8FWgICumZTQA+EIHDSCUPs=,tag:xMHVm3XtnDHb9nmBU+w/iQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rf6mvs2deuyrv34qsl5ftq7tfvs8f9f3d5f4y63hjcpgznyuc42qj6ep8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6aWlvZDNhODIzNXJXakoz
            ZWJ6OEhIQ2VmVDVQV2dyQjhpTXU0ZFBsdkNZCnREZmRNSXRXUUlPNTVUQlp6c2ZZ
            c2c4V0hwZHc4NjJlR0VUUVhHN04zelEKLS0tIEFUZ1pCalVjMm5Tc29jNGQ5L1Vy
            SjJIbFJ2R0dJaytCTGZpVDhPMFVWMFEKevOiJiO8VoFmiknxMuMUl8QMfqD/AVAo
            6THVnNxZCGS24T+rkchzkDxP8rw2bsUPMvnWkeJGmFS+6yl/SkZ0/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-11T11:11:59Z"
    mac: ENC[AES256_GCM,data:GgtO3zYGai7zH6s5ul9/3H5VMt2llO7N+syR++TN1xxWuMZ25qGCc+KfRnSq8C6SzTJCYkZJMGYbW5l/nuPIQYbeITb2VtcvsM2qlyMUbnpx8og4JgU0JhWVDzuGooGHWhluq6YYMrOsDNCcAr+10/4oe2vnHs0MvzA8qSKAw50=,iv:ldsNTICw43hXXPFhAn44+xGOxekWl51ClP2pEoriMng=,tag:QLRkxzawyExdFCYm5KaVQw==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
