version: '1.0'
services:
  ping-pong:
    image: katushka/ping-pong:1.3
    build:
      context: ../ping-pong
      dockerfile: Dockerfile
  log-output:
    image: katushka/log-output:1.5
    build:
      context: ../log-output
      dockerfile: Dockerfile
  timestamp-generator:
    image: katushka/timestamp-generator:1.1
    build:
      context: ../timestamp-generator
      dockerfile: Dockerfile